### ISSUE TITLE
Inline CSS

### ISSUE THREAD

**Issue by parasm** [LeChosenOne/lechosenone.github.io#1]
Please don't use inline, its poor quality code
-stan the man

**Comment by J-Wass** [comment]
Thanks for creating an issue for fungi.ml

We appreciate your interest in this project. At this time, we are no longer actively looking issues. We are still looking for a number of other issues in other projects, and hope that you will continue your search with us. Continue to check our projects at github.com to search for and write for other issues.

Thanks again for considering us.

fungi.ml
